name: Sergey Gavruk Blog
# description: Blogging about stuffs
meta_description: "Sergey Gavruk Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'gavruk.com'
author:         'Sergey Gavruk'
